name: Backend CI

on:
  push:
    branches: [master]
    paths:
      - "backend/**"
  pull_request:
    branches: [master]
    paths:
      - "backend/**"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "npm"
          cache-dependency-path: "./backend/package-lock.json"

      - name: Install dependencies
        run: npm ci

      # I notice you have ESLint installed but no script defined
      - name: Run ESLint
        run: npx eslint . --ext .ts

      # Separate type checking step
      - name: TypeScript Check
        run: npx tsc --noEmit

      # Then build after validation passes
      - name: Build
        run: npm run build

      # Security scan for dependencies
      - name: Security audit
        run: npm audit --production
